#!/bin/bash
VERSION=`pg_lsclusters -h|awk '{print $1}'`

if [[ ! "$(ls -A $DATA_DIR)" ]]; then
    cp -a /var/lib/postgresql/$VERSION/main/. $DATA_DIR
fi

/sbin/setuser postgres /usr/lib/postgresql/$VERSION/bin/postgres -D $DATA_DIR \
    -c config_file=/etc/postgresql/$VERSION/main/postgresql.conf \
     >> /var/log/postgresql/postgresql-$VERSION-main.log 2>&1
